import fs from 'node:fs'
import path from 'node:path'

const source = fs.readFileSync(path.join(process.cwd(), 'src/views/blog/BlogHome.vue'), 'utf8')
const layoutSource = fs.readFileSync(path.join(process.cwd(), 'src/layouts/BlogLayout.vue'), 'utf8')
const indexSource = fs.readFileSync(path.join(process.cwd(), 'index.html'), 'utf8')

describe('focused warm technology blog homepage', () => {
  it('keeps only the hero, latest articles, topics, and shared footer structure', () => {
    expect(source).toContain('class="home-hero"')
    expect(source).toContain('id="latest-posts"')
    expect(source).toContain('id="topics"')
    expect(layoutSource).toContain('<footer class="site-footer">')
    expect(source).not.toContain('visual-ribbon')
    expect(source).not.toContain('manifesto-carousel')
    expect(source).not.toContain('tag-marquee')
    expect(source).not.toContain('final-cta')
    expect(source).not.toContain('bento-grid')
  })

  it('uses a text-first hero and article list without homepage images', () => {
    expect(source).toContain('aria-label="探索技术，无限可能，开发、构建、应用"')
    expect(source).toContain('class="article-list"')
    expect(source).toContain('v-for="item in latest"')
    expect(source).not.toContain('<img')
    expect(source).not.toContain('getHotDynamics')
    expect(source).not.toContain('getBlogTagList')
    expect(source).not.toContain('class="eyebrow"')
    expect(source).not.toContain('class="hero-description"')
    expect(source).not.toContain('class="hero-actions')
  })

  it('provides a first-screen hero with a static title and scroll guidance', () => {
    expect(source).toContain('aria-label="滚动到最新文章"')
    expect(source).toContain('href="#latest-posts"')
    expect(source).toContain('id="latest-posts"')
    expect(source).toContain('min-height: calc(100dvh - var(--header-height))')
    expect(source).toContain('white-space: nowrap')
    expect(source).toContain('class="hero-inner app-container"')
    expect(source).toContain('background: #f5efe5;')
    expect(source).toContain('.home-hero { position: relative; display: flex; width: 100%;')
    expect(source).toContain('justify-content: center')
    expect(layoutSource).toContain('.blog-shell--home .site-header')
    expect(layoutSource).toContain('.blog-shell--home .site-main')
    expect(layoutSource).toContain('position: fixed')
    expect(source).not.toContain('hero-particle-canvas')
    expect(source).not.toContain('hero-atmosphere')
    expect(source).not.toContain('hero-light-sheet')
    expect(source).not.toContain('hero-trace')
    expect(source).not.toContain('startParticleTitle')
    expect(source).not.toContain('titleReady')
  })

  it('uses the lazy Inspira fluid cursor and a typewriter title instead of the old particle trail', () => {
    expect(source).toContain('const FluidCursor = defineAsyncComponent')
    expect(source).toContain('<FluidCursor v-if="fluidCursorVisible"')
    expect(source).toContain('class="hero-fluid-wash"')
    expect(source).toContain('@pointerenter="activateFluidCursor"')
    expect(source).toContain('sim-resolution="64"')
    expect(source).toContain('dye-resolution="480"')
    expect(source).toContain('pressure-iterations="10"')
    expect(source).toContain('fluidCursorVisible')
    expect(source).toContain('typedLead')
    expect(source).toContain('typedAccent')
    expect(source).toContain('startTitleTyping')
    expect(source).toContain('prefers-reduced-motion')
    expect(source).not.toContain('heroEffectCanvas')
    expect(source).not.toContain('heroStreaks')
    expect(source).not.toContain('heroBurstStars')
    expect(source).not.toContain('handleHeroClick')
    expect(source).not.toContain('addHeroBurst')
    expect(source).not.toContain('hero-fluid-canvas')
  })

  it('gives the title a calm, variable-speed typewriter finish and breathing afterglow', () => {
    expect(source).toContain('titlePhase')
    expect(source).toContain('titlePhase.value = \'settling\'')
    expect(source).toContain('titlePhase.value = \'breathing\'')
    expect(source).toContain('leadDelays')
    expect(source).toContain('typeDelays')
    expect(source).toContain('class="hero-title-loop__cursor"')
    expect(source).toContain('hero-title--settling')
    expect(source).toContain('hero-title--breathing')
    expect(source).toContain('hero-title-settle')
    expect(source).toContain('hero-title-breathe')
    expect(source).toContain('titleSettleTimer')
    expect(source).toContain('window.clearTimeout(titleSettleTimer)')
  })

  it('keeps the main title intact and appends a separate looping typewriter suffix', () => {
    expect(source).toContain("const accent = '无限可能'")
    expect(source).toContain("const trailWords = ['开发', '构建', '应用']")
    expect(source).toContain('typedTrail')
    expect(source).toContain('trailPhase')
    expect(source).toContain('scheduleTrailCycle')
    expect(source).toContain('trailTimer')
    expect(source).toContain("trailPhase.value = 'deleting'")
    expect(source).toContain("trailPhase.value = 'typing'")
    expect(source).toContain('hero-title-loop')
    expect(source).toContain('hero-title-loop__word')
    expect(source).toContain('hero-title-loop__cursor')
    expect(source).not.toContain('hero-title__prompt')
  })

  it('defers topic data and below-fold rendering until it is near the viewport', () => {
    expect(source).toContain('content-visibility: auto')
    expect(source).toContain('contain-intrinsic-size: 720px')
    expect(source).toContain('IntersectionObserver')
    expect(source).toContain("rootMargin: '240px 0px'")
    expect(source).toContain('loadCategories()')
  })

  it('keeps the warm visual language restrained on the homepage', () => {
    expect(source).toContain('--home-accent: #b85e2d')
    expect(source).toContain('border-radius: 999px')
    expect(source).toContain('prefers-reduced-motion: reduce')
    expect(layoutSource).toContain("v-if=\"route.name !== 'BlogHome'\"")
  })

  it('uses a dedicated readable favicon instead of shrinking the detailed brand mark', () => {
    expect(indexSource).toContain('favicon-coffee-v2.svg')
    expect(indexSource).toContain('type="image/svg+xml"')
    expect(indexSource).not.toContain('logo-coffee-code.png" />')
  })
})
